#!/usr/bin/env bash
# orchestrator.sh — Deploy and manage collectors across lab machines
#
# Manages switch machines automatically. The wire machine runs
# independently because it's on a separate physical network.
#
# Reads all config from config.toml (generated by setup_wizard.py).
#
# Usage:
#   ./orchestrator.sh {deploy|start|stop|status|collect}
#
# First-time setup:
#   python3 setup_wizard.py    # generates config.toml
#   ./orchestrator.sh start    # starts switch machines
#   # Then start the wire machine collector manually (instructions printed)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ─── Load configuration from config.toml ─────────────────────────────
if ! python3 "$SCRIPT_DIR/load_config.py" > /dev/null 2>&1; then
    echo "ERROR: Could not read config.toml"
    echo "  Run: python3 setup_wizard.py"
    exit 1
fi

eval "$(python3 "$SCRIPT_DIR/load_config.py")"

COLLECT_DIR="${COLLECT_DIR:-./all_results}"

# ─── Helpers ──────────────────────────────────────────────────────────
info()  { echo "  [INFO]  $*"; }
ok()    { echo "  [  OK]  $*"; }
warn()  { echo "  [WARN]  $*"; }
fail()  { echo "  [FAIL]  $*"; }

ssh_cmd() {
    local host="$1"
    shift
    ssh -o ConnectTimeout=5 -o BatchMode=yes "${DEST_USER}@${host}" "$@" 2>/dev/null
}

# ─── Deploy ───────────────────────────────────────────────────────────
do_deploy() {
    echo "Deploying fileiotest to ${#SWITCH_MACHINES[@]} switch machines..."
    echo ""

    for host in "${SWITCH_MACHINES[@]}"; do
        printf "  %-12s " "$host"
        ssh -f -o ConnectTimeout=5 -o BatchMode=yes "${DEST_USER}@${host}" \
            "cd ${DEPLOY_DIR} && \
            nohup env \
                NUM_FILES='${NUM_FILES}' \
                INTERVAL_MIN='${INTERVAL_MIN}' \
                DURATION_HR='${DURATION_HR}' \
                PING_COUNT='${PING_COUNT}' \
                SOURCE_LABEL='${host}' \
                RESULTS_DIR='${DEPLOY_DIR}/collector_results' \
            bash ./collector.sh '${DEST}' \
                > ${DEPLOY_DIR}/collector_${host}.log 2>&1 </dev/null &" \
        && ok "started" \
          || fail "launch failed"
    done

    DAYS=$(( DURATION_HR / 24 ))
    echo ""
    echo "═══════════════════════════════════════════════════════════════════"
    echo "  Switch machines launched. They will run for ${DAYS} days."
    echo ""
    echo "  Use '$0 status' to check progress."
    echo "  Use '$0 stop' to stop early."
    echo "  Use '$0 collect' to gather results."
    echo "═══════════════════════════════════════════════════════════════════"
    echo ""
    echo "┌─────────────────────────────────────────────────────────────────┐"
    echo "│  WIRE CONNECTION: ${WIRE_SOURCE_MACHINE} must be started separately."
    echo "│"
    echo "│  SSH into ${WIRE_SOURCE_MACHINE}, clone the repo, run the wizard, then:"
    echo "│"
    echo "│    cd ${DEPLOY_DIR}"
    echo "│    nohup env \\"
    echo "│      NUM_FILES='${NUM_FILES}' \\"
    echo "│      INTERVAL_MIN='${INTERVAL_MIN}' \\"
    echo "│      DURATION_HR='${DURATION_HR}' \\"
    echo "│      PING_COUNT='${PING_COUNT}' \\"
    echo "│      SOURCE_LABEL='${WIRE_SOURCE_MACHINE}' \\"
    echo "│    bash ./collector.sh '${DEST_USER}@${WIRE_DEST_IP}' \\"
    echo "│      > collector_${WIRE_SOURCE_MACHINE}.log 2>&1 &"
    echo "│"
    echo "│  Start this at roughly the same time as the switch machines."
    echo "└─────────────────────────────────────────────────────────────────┘"
    echo ""
}

# ─── Stop ─────────────────────────────────────────────────────────────
do_stop() {
    echo "Stopping collectors on switch machines..."
    echo ""

    for host in "${SWITCH_MACHINES[@]}"; do
        printf "  %-12s " "$host"
